#!/bin/bash

echo "=============================================="
echo "    TESTES MANUAIS - SUPER TRUNFO"
echo "=============================================="
echo ""
echo "Este script testa entradas inválidas que requerem interação manual."
echo "Execute cada teste seguindo as instruções."
echo ""

# Compilar o programa original
echo "Compilando o programa Super Trunfo..."
gcc -o super_trunfo super_trunfo.c -lm

if [ $? -ne 0 ]; then
    echo "❌ Erro na compilação do programa principal!"
    exit 1
fi

echo "✅ Programa compilado com sucesso!"
echo ""

echo "================================================"
echo "TESTE 1: ENTRADA INVÁLIDA NO MENU PRINCIPAL"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Pressione Enter na tela inicial"
echo "3. No menu, teste as seguintes entradas inválidas:"
echo "   - Digite 'a' e pressione Enter"
echo "   - Digite '0' e pressione Enter"
echo "   - Digite '5' e pressione Enter"
echo "   - Digite '-1' e pressione Enter"
echo "   - Digite '1.5' e pressione Enter"
echo "   - Pressione apenas Enter (entrada vazia)"
echo "4. Verifique se o programa solicita nova entrada para cada caso"
echo "5. Digite '4' para sair"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 2: ENTRADA INVÁLIDA NA SELEÇÃO DE CARTAS"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Pressione Enter e escolha '1' (Iniciar Jogo)"
echo "3. Na seleção de cartas, teste:"
echo "   - Digite '0' e pressione Enter"
echo "   - Digite '9' e pressione Enter"
echo "   - Digite 'abc' e pressione Enter"
echo "   - Digite '-1' e pressione Enter"
echo "4. Escolha uma carta válida (1-8) e confirme com 'S'"
echo "5. Repita o processo para o Jogador 2"
echo "6. Tente escolher a mesma carta do Jogador 1"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 3: CONFIRMAÇÃO DE CARTA INVÁLIDA"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Inicie o jogo e escolha uma carta válida"
echo "3. Na confirmação, teste:"
echo "   - Digite 'x' e pressione Enter"
echo "   - Digite '1' e pressione Enter"
echo "   - Digite 'abc' e pressione Enter"
echo "   - Pressione apenas Enter"
echo "4. Digite 'N' para recusar e escolher outra carta"
echo "5. Escolha novamente e confirme com 'S'"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 4: ENTRADA INVÁLIDA NA SELEÇÃO DE ATRIBUTOS"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Inicie o jogo e escolha cartas para ambos jogadores"
echo "3. Na seleção do primeiro atributo, teste:"
echo "   - Digite '0' e pressione Enter"
echo "   - Digite '8' e pressione Enter"
echo "   - Digite 'abc' e pressione Enter"
echo "   - Digite '-1' e pressione Enter"
echo "4. Escolha um atributo válido (1-7)"
echo "5. Para o segundo atributo, tente escolher o mesmo do primeiro"
echo "6. Escolha um atributo diferente e válido"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 5: TESTE DE REGRAS"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Escolha '2' (Ver regras)"
echo "3. Teste entradas inválidas:"
echo "   - Digite 'a' e pressione Enter"
echo "   - Digite '0' e pressione Enter"
echo "   - Digite '2' e pressione Enter"
echo "4. Digite '1' para voltar ao menu"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 6: TESTE COMPLETO DE JOGO"
echo "================================================"
echo "Instruções:"
echo "1. Execute um jogo completo com entradas válidas"
echo "2. Teste diferentes combinações de cartas e atributos"
echo "3. Verifique se os cálculos estão corretos"
echo "4. Teste o critério de desempate"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTE 7: BUFFER OVERFLOW"
echo "================================================"
echo "Instruções:"
echo "1. Execute: ./super_trunfo"
echo "2. Tente inserir strings muito longas no menu"
echo "3. Digite sequências longas de caracteres (ex: aaaaaaaaaaaaaaaaaaaaaa)"
echo "4. Verifique se o programa não trava ou corrompe"
echo ""
read -p "Pressione Enter para executar este teste..."
./super_trunfo

echo ""
echo "================================================"
echo "TESTES MANUAIS CONCLUÍDOS"
echo "================================================"
echo "Os testes manuais foram executados."
echo "Verifique se todos os comportamentos estão adequados:"
echo ""
echo "✅ Checklist de validação:"
echo "□ Entradas inválidas são rejeitadas adequadamente"
echo "□ Mensagens de erro são claras e informativas"
echo "□ O programa não trava com entradas inesperadas"
echo "□ A navegação entre menus funciona corretamente"
echo "□ Os cálculos matemáticos estão corretos"
echo "□ A lógica de comparação funciona adequadamente"
echo "□ O critério de desempate está implementado"
echo "□ As validações de intervalo funcionam"
echo "□ O programa lida bem com buffers longos"
echo ""
echo "Se todos os itens foram verificados, o programa passou"
echo "em todos os testes de validação!"